feat: add `#[track_caller]` to functions that panic  (#748)
While using `Acyclic` I got this panic:

```
thread 'tests::panic_on_short_cycle' panicked at /home/marcospb19/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/petgraph-0.7.1/src/graphmap.rs:1203:38:
called `Option::unwrap()` on a `None` value
```

While expected, it'd be more helpful if it pointed to the caller in my
code, not the upstream code.

I started adding `#[track_caller]` for `Acyclic` and ended up going
through all functions that contain "panics" in their docs, except for
`std::ops::Index[Mut]` cause those have `#[track_caller]` in the trait
definition.