refactor: Remove unnecessary trait bounds from impls/methods (#828)
The goal of this PR is to make the following scenario possible:

```rust
#[derive(Default, Clone)]
struct DummyWrapper<Node, Edge, Ix> {
    graph: StableDiGraph<Node, Edge, Ix>,
}
```

… which currently requires a manual implementation of both, `Default`
and `Clone`:

```rust
struct DummyWrapper<Node, Edge, Ix> {
    graph: StableDiGraph<Node, Edge, Ix>,
}

impl<Node, Edge, Ix> Clone for DummyWrapper<Node, Edge, Ix>
where
    Node: Clone,
    Edge: Clone,
    Ix: Clone,
{
    fn clone(&self) -> Self {
        Self {
            graph: self.graph.clone(),
        }
    }
}

impl<Node, Edge, Ix> Default for DummyWrapper<Node, Edge, Ix>
where
    Node: Default,
    Edge: Default,
    Ix: Default,
{
    fn default() -> Self {
        Self {
            graph: Default::default(),
        }
    }
}
```

… due to the following trait bounds getting in the way of the derives:

```
error[E0277]: the trait bound `Ix: petgraph::adj::IndexType` is not satisfied
 --> web-api/crates/interactive-graph/src/lib.rs:3:5
  |
1 | #[derive(Default, Clone)]
  |          ------- in this derive macro expansion
2 | struct DummyWrapper<Node, Edge, Ix> {
3 |     graph: StableDiGraph<Node, Edge, Ix>,
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `petgraph::adj::IndexType` is not implemented for `Ix`

error[E0277]: the trait bound `Ix: petgraph::adj::IndexType` is not satisfied
 --> web-api/crates/interactive-graph/src/lib.rs:3:5
  |
1 | #[derive(Default, Clone)]
  |                   ----- in this derive macro expansion
2 | struct DummyWrapper<Node, Edge, Ix> {
3 |     graph: StableDiGraph<Node, Edge, Ix>,
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `petgraph::adj::IndexType` is not implemented for `Ix`
```

With this PR's changes the initial scenario compiles as is, using
derives.